Simulation and Modeling Lab  
**Course Code:** CSE 413  
Lab Task 1


In [13]:
import numpy as np

# ==========================================
# Step 1: Create Matrix A (3x3 Random Integer Matrix)
# ==========================================

A = np.random.randint(1, 10, (3, 3))

print("Matrix A:\n", A)
print("--------------------------------------------------")

# ==========================================
# Step 2: Analyze Matrix A
# ==========================================

# Shape
size_A = A.shape

# Determinant
det_A = np.linalg.det(A)

# Rank
rank_A = np.linalg.matrix_rank(A)

# Eigenvalues
eival_A = np.linalg.eigvals(A)

# Inverse (Safe floating comparison)
if not np.isclose(det_A, 0):
    inv_A = np.linalg.inv(A)
else:
    inv_A = "Matrix A is singular, cannot compute inverse"

print("Shape of Matrix A:", size_A)
print("Determinant of Matrix A:", det_A)
print("Rank of Matrix A:", rank_A)
print("Eigenvalues of Matrix A:", eival_A)
print("Inverse of Matrix A:\n", inv_A)

print("==================================================")

# ==========================================
# Step 3: Value Change Experiment
# Change exactly ONE value in A (+1)
# ==========================================

B = A.copy()

# Change element at position (0,0) by adding +1
B[0, 0] = B[0, 0] + 1

print("Matrix B (Changed element A[0,0] + 1):\n", B)
print("--------------------------------------------------")

# ==========================================
# Step 4: Analyze Matrix B
# ==========================================

# Shape
size_B = B.shape

# Determinant
det_B = np.linalg.det(B)

# Rank
rank_B = np.linalg.matrix_rank(B)

# Eigenvalues
eival_B = np.linalg.eigvals(B)

# Inverse
if not np.isclose(det_B, 0):
    inv_B = np.linalg.inv(B)
else:
    inv_B = "Matrix B is singular, cannot compute inverse"

print("Shape of Matrix B:", size_B)
print("Determinant of Matrix B:", det_B)
print("Rank of Matrix B:", rank_B)
print("Eigenvalues of Matrix B:", eival_B)
print("Inverse of Matrix B:\n", inv_B)


Matrix A:
 [[5 8 7]
 [5 6 9]
 [6 3 1]]
--------------------------------------------------
Shape of Matrix A: (3, 3)
Determinant of Matrix A: 139.99999999999994
Rank of Matrix A: 3
Eigenvalues of Matrix A: [16.60339615+0.j         -2.30169807+1.77036602j -2.30169807-1.77036602j]
Inverse of Matrix A:
 [[-0.15        0.09285714  0.21428571]
 [ 0.35       -0.26428571 -0.07142857]
 [-0.15        0.23571429 -0.07142857]]
Matrix B (Changed element A[0,0] + 1):
 [[6 8 7]
 [5 6 9]
 [6 3 1]]
--------------------------------------------------
Shape of Matrix B: (3, 3)
Determinant of Matrix B: 118.99999999999993
Rank of Matrix B: 3
Eigenvalues of Matrix B: [17.+0.j         -2.+1.73205081j -2.-1.73205081j]
Inverse of Matrix B:
 [[-0.17647059  0.1092437   0.25210084]
 [ 0.41176471 -0.30252101 -0.15966387]
 [-0.17647059  0.25210084 -0.03361345]]


5. Comparison & Explanation
Answer the following in your own words:

1. How did the determinant change and why?
ans:
Det(A) = 7 × 8 − 7 × 10 = 56 − 70 = −14
Det(B) = 8 × 8 − 7 × 10 = 64 − 70 = −6

The change is that determinant increased from −14 to −6.
Why did it happen? Because I increased the value of the top-left element on Matrix B.
So, increasing the product on the diagonal made the determinant less negative on Matrix B.

2. Did the rank change? Explain.
ans:
The simple answer is no.
Both Matrix A and Matrix B have the same rank as both determinants are non-zero.

3. How did the eigenvalues respond to the value change?
ans:
The eigenvalues have changed a little but are still significant if we compare the eigenvalues of Matrix A and Matrix B.
This happened because of the change in Matrix B's diagonal element, which in this case is the first element (top-left element).

4. Is B easier or harder to invert than A? Why?
ans:
Matrix B is a little harder to invert than Matrix A.
This is because Matrix B is closer to singular than Matrix A.
In other words, Matrix B's inverse has larger values than Matrix A's, making Matrix B's inverse less stable.